### ISSUE TITLE
Add ability to animate page change when page index is changed programmatically

### ISSUE THREAD

**Issue by socachaser** [gh123man/SwiftUI-LazyPager#12]
Would it be possible to animate the page change when the index is changed programmatically? Right now if I change the index, the page updates without animation, however there are cases here I would like to animate the page changing.

**Comment by gh123man** [comment]
Do you envision animating only previous and next page? Or skipping `n` pages. For example, going form `0` -> `5` and having it scroll past 4 images?

**Comment by socachaser** [comment]
I would envision being able to skip `n` pages. In my head I'm picturing using the `LazyPager` for a photo viewer, but also having a custom horizontal `ScrollView` where the user can display the thumbnail photos which the user can click on a thumbnail to view the photo.

**Comment by gh123man** [comment]
Makes sense! 
here's what I got so far:

https://github.com/user-attachments/assets/11044ca4-eb2c-4339-8bc4-75d12e9a96c7

It works for arbitrary offsets. However if you skip > [`preloadAmount`](https://github.com/gh123man/SwiftUI-LazyPager/blob/master/Sources/LazyPager/LazyPager.swift#L65), it will load the next set of images first before animating, which is hardly noticeable unless you slow the animation down. 

Let me know if this is good enough for your use case. 
The problem with animating truly `n` images is if `n = 10000` it would be computationally expensive and the animation would likely lag or freeze. With the current implementation you can increase `preloadAmount` to smooth it out if you want.

**Comment by socachaser** [comment]
That does look like it will work for what I need. It does make sense that you won't want to load all of the images if `n = 1000`.

**Comment by gh123man** [comment]
Awesome. Thanks for the feedback. ill clean this up and put it in the next release!

**Comment by gh123man** [comment]
Released in `1.1.3`

[Full example here](https://github.com/gh123man/SwiftUI-LazyPager/blob/master/Examples/LazyPagerExampleApp/AnimatedPagerControlsExample.swift)

You can now use `withAnimation` when setting the page and `LazyPager` will animate the transition.

**Comment by socachaser** [comment]
Thank you, but one small item is with the updated build there is a blank space below the `LazyPager` where there wasn't before.

**Comment by gh123man** [comment]
Darn. This is likely from me [trying to fix content inset adjustments. ](https://github.com/gh123man/SwiftUI-LazyPager/commit/389c0e131fa39df7e9f50394f0f2a13632b63366). 

Are you by any chance using `.ignoresSafeArea()`?

**Comment by gh123man** [comment]
Ive reverted the change that tries to fix the content inset adjustments. 
As a result, on iOS 18 using the view in landscape with safe areas is broken. This appears to be a regression with iOS 18 as it didn't happen on 17. 

Ill continue to investigate but I released 1.1.4 with the inset changes removed.

**Comment by gh123man** [comment]
I figured it out. Released in `1.1.5`. 
Thanks again
