### ISSUE TITLE
Tab Bar background suddenly disappears

### ISSUE THREAD

**Issue by fl034** [gh123man/SwiftUI-LazyPager#16]
First of all, thanks so much for this lovely library! Saved me a lot of time.

I'm having a strange bug: The first time I start swiping through LazyPager in my Newsfeed, my tab bar background suddenly disappears. Switching tabs and coming back it's resolved, until it happens again in another instance.

I've tried setting anything tab bar related, setting scrollEdgeAppearance and so on, but it all comes down to the use of LazyPager. When I replace it with a native TabView, the bug is gone again.

It's nested inside GeometryReader → ScrollView → LazyVStack

Looking at your code, I can't see anything that could trigger this bug. Do you?

![Simulator Screen Recording - iPhone 16 - 2024-12-18 at 17 50 46](https://github.com/user-attachments/assets/b4cae38e-22a6-45cb-b633-b33f3e07f452)

Maybe I can create a minimal working example that you can analyze or I can use a Apple code level support ticket.

**Comment by gh123man** [comment]
Hey, Thanks for reaching out. 

I think I can reproduce this. However I think it's an odd behavior of SwiftUI (unclear if it's a bug or not). 

Here is some code based off of the [simple example app](https://github.com/gh123man/SwiftUI-LazyPager/blob/master/Examples/LazyPagerExampleApp/SimpleExample.swift) in the repo. 

It seems the tab bar becomes fully transparent when: the contained view overflows and is not in a scroll view. 
Below I can repro the same behavior with both `LazyPager` and a simple `Image` view. 

```swift
import SwiftUI
import LazyPager
struct SimpleExample: View {
    
    @State var data = [
        "nora1",
        "nora2",
        "nora3",
        "nora4",
        "nora5",
        "nora6",
    ]
    
    @State var show = false
    @State private var selectedTab = 0
    
    var body: some View {
        TabView(selection: $selectedTab) {
            
            Image("nora1")
            .tabItem {
                Image(systemName: "x.circle.fill")
                Text("broken")
            }
            
            ScrollView {
                Image("nora1")
            }
            .tabItem {
                Image(systemName: "checkmark.seal.fill")
                Text("Works")
            }
            
            
            LazyPager(data: data) { element in
                Image(element)
            }
            .ignoresSafeArea()
            .tabItem {
                Image(systemName: "x.circle.fill")
                Text("broken")
            }
            
            ScrollView {
                VStack {
                    LazyPager(data: data) { element in
                        Image(element)
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                    }
                    .zoomable(min: 1, max: 10)
                    .ignoresSafeArea()
                    .frame(width: 500, height: 900)
                }
            }
            .tabItem {
                Image(systemName: "checkmark.seal.fill")
                Text("Works")
            }
            .tag(1)

            
        }
        .background(.red)
        
    }
}

struct SimpleExample_Previews: PreviewProvider {
    static var previews: some View {
        SimpleExample()
    }
}
```

<img width="250" alt="image" src="https://github.com/user-attachments/assets/4fe18510-a158-4c3e-a7d9-40470a8a6cb1" />
<img width="250" alt="image" src="https://github.com/user-attachments/assets/8ad36477-4cb7-4c36-89a2-e648334e7c77" />
<img width="250" alt="image" src="https://github.com/user-attachments/assets/e40f3280-0e1a-459a-a439-ffb072af2b2f" />
<img width="250" alt="image" src="https://github.com/user-attachments/assets/e15095da-6329-4323-8e73-3dd5c36fa3ac" />

Let me know if this helps or if you are seeing a different issue. I am happy to further investigate.

**Comment by fl034** [comment]
Hi Brian, thanks for your in-depth answer here. I guess the cases in your example are related. 
After some more research I stumbled upon the modifier `.toolbarBackground(.visible, for: .tabBar)` which fixes the bug 🎉 .
In my case somehow the system thinks the nested scrollview of LazyPager is the one it should use for determining if the tab bar background should be hidden 🤷🏽‍♂️.
Interestingly the good old UIAppearance APIs didn't change anything about the behavior.
