### ISSUE TITLE
 display video content, preloaded elements will be call onAppear

### ISSUE THREAD

**Issue by zkamisama** [gh123man/SwiftUI-LazyPager#4]
If the video content is displayed and the 3 elements before and after the current index are preloaded, there will be a call to onAppear, how to control the video content to trigger onAppear to load the video only when it appears on the screen?

Or add an index value to the content closure callback parameter so that I can control it by comparing the current index

**Comment by gh123man** [comment]
You can use the bound index variable `LazyPager(data: data, page: $index)` which should be set to the current page. 

```swift
@State var index = 0
...

LazyPager(data: data, page: $index) { element in
    // video view
}
.onChange(of: index) { val in
    print(val) // Only prints the currently displayed index
}

```

let me know if this works for you
