### ISSUE TITLE
Issue with LazyPager not displaying network images correctly on swipe

### ISSUE THREAD

**Issue by Corotata** [gh123man/SwiftUI-LazyPager#7]
Hey!

**Description:**
When using `LazyPager` for image preview, local images switch correctly to the next image. However, when using `AsyncImage(url: URL(string: imageUrls[currentIndex]))` or `KFImage(URL(string: imageUrls[currentIndex]))` to load network images, the next image does not display correctly during the swipe transition.

**Steps to Reproduce:**
1. Implement `LazyPager` to display a list of images, including URLs for network images.
2. Swipe to switch to the next image.
3. Observe that while local images load correctly, the network images fail to display properly.

**Expected Behavior:**
The next network image should load and display correctly when swiping to it, similar to the behavior of local images.

**Question:** Is there a potential misuse of the library or configuration on my part that could be causing this issue? 
Thank you.

https://github.com/user-attachments/assets/efa5cc21-8c3d-48b9-8267-2911604c2c56

Code Example:
```swift
struct ImageDetailView: View {
    var imageUrls: [String] = []
    @State var currentIndex: Int
    @State private var scale: CGFloat = 1.0
    @State private var isToolbarVisible: Bool = true
    @State var show = true
    @State var opacity: CGFloat = 1
    
    var body: some View {
        VStack {
            LazyPager(data: ["nora1","nora2","nora3","nora4"], page: $currentIndex, direction: .horizontal) { element in
                ZStack {
                    Image(element)
                        .resizable()
                        .aspectRatio(contentMode: .fit)
                    
                }
            }
            LazyPager(data: imageUrls, page: $currentIndex, direction: .horizontal) { element in
                ZStack {
                    AsyncImage(url: URL(string: imageUrls[currentIndex]))
                        .aspectRatio(contentMode: .fit)
//                    KFImage(URL(string: imageUrls[currentIndex]))
//                        .resizable()
//                        .aspectRatio(contentMode: .fit)
                    
                }
            }
            .zoomable(min: 1, max: CGFloat(imageUrls.count))
            .onDismiss(backgroundOpacity: $opacity) {
                show = false
            }
            .onTap {
                print("tap")
            }
            //            .shouldLoadMore(on: .lastElement(minus: 2)) {
            //                // data.append(Foo(img: "nora4", idx: data.count))
            //            }
            .background(.black.opacity(opacity))
            .background(ClearFullScreenBackground())
            .ignoresSafeArea()
        }
    }
}


#Preview {
    ImageDetailView(imageUrls: [
        "https://act-upload.mihoyo.com/wiki-user-upload/2024/08/27/258999284/edc282bd8955faa88895b23c4061a2f5_2301203435965777916.png?x-oss-process=image/quality,q_75/resize,s_224", "https://act-upload.mihoyo.com/wiki-user-upload/2024/08/27/258999284/25d2e76748611db680909e98c1629e41_6781309789721202832.png?x-oss-process=image/quality,q_75/resize,s_224", "https://act-upload.mihoyo.com/wiki-user-upload/2024/08/27/258999284/79deea8fbb624269dc7a85fb22bbf649_1852262329670390843.png?x-oss-process=image/quality,q_75/resize,s_224"
    ], currentIndex: 0)
}

```

**Comment by Corotata** [comment]
Hi @gh123man 

Just as you mentioned, thank you for your response.

Do you have any plans to support macOS for this library in the future?

**Comment by gh123man** [comment]
> Do you have any plans to support macOS for this library in the future?

Unfortunately I do not. Since this library depends heavily on UIKit and iOS view primitives it would be a non-trivial effort to bring support to macOS/AppKit. I'm sure it's possible to some degree and would be happy to take a contributor PR to add such support.

Thanks again for reaching out. Since it seems your problem is resolved, I'm going to close this issue.
