### ISSUE TITLE
Crash. Index out of range.

### ISSUE THREAD

**Issue by DmitriyTerekhin** [gh123man/SwiftUI-LazyPager#9]
When try scroll out of last.
<img width="1059" alt="Screenshot 2024-10-16 at 19 47 58" src="https://github.com/user-attachments/assets/6f2594e1-805b-4a1f-8714-f20fbb8a3eb2">

**Comment by gh123man** [comment]
Thanks for reporting this. 

Fixed in  https://github.com/gh123man/SwiftUI-LazyPager/releases/tag/1.1.1
